### PR TITLE
Simple naive hooks implementation

### PR DESCRIPTION
**Pull request by marcopiraccini**

### CODE REVIEW

**Review by ShogunPanda — APPROVED** [review]
LGTM, very nice!

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add this to the Readme?

**Comment by marcopiraccini** [comment]
@mcollina @ShogunPanda PTAL

**Review by ShogunPanda — APPROVED** [review]
LGTM!

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
